/**
 * Login Screen Action Types
 */
export const ADD_LOGIN_DETAILS = 'ADD_LOGIN_DETAILS';
export const UPDATE_LOGIN_DETAILS = 'UPDATE_LOGIN_DETAILS';
export const DELETE_LOGIN_DETAILS = 'DELETE_LOGIN_DETAILS';

/**
 * MyCollection Screen Action Types
 */
export const ADD_COLLECTION_DETAILS = 'ADD_COLLECTION_DETAILS';
export const UPDATE_COLLECTION_DETAILS = 'UPDATE_COLLECTION_DETAILS';
export const DELETE_COLLECTION_DETAILS = 'DELETE_COLLECTION_DETAILS';

/**
 * RequestBook Screen Action Types
 */
export const ADD_BOOKREQUEST_DETAILS = 'ADD_BOOKREQUEST_DETAILS';
export const UPDATE_BOOKREQUEST_DETAILS = 'UPDATE_BOOKREQUEST_DETAILS';
export const DELETE_BOOKREQUEST_DETAILS = 'DELETE_BOOKREQUEST_DETAILS';